name: flutter_blue_example
description: Demonstrates how to use the flutter_blue plugin.
version: 0.0.1+1
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  meta: ^1.1.8
  equatable: ^1.2.0
  flutter_bloc: ^4.0.1
  fimber: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_blue: ^0.7.2
#    path: ../
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
